ARG IMAGE=ubuntu20.04
FROM ${IMAGE}

ENV DEBIAN_FRONTEND="noninteractive"

ARG ROS1_DISTRO=noetic
ARG ROS2_DISTRO=foxy

#
# Install necessary packages
#
RUN apt-get update && apt-get install -y \
    apt-utils \
    sudo \
    curl \
    gnupg2 \
    python3 \
    vim \
    lsb-release \
    locales && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

#
# ROS 1 installation
#
RUN sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update && apt-get install -y \
    ros-$ROS1_DISTRO-desktop-full \
    python3-rosdep \
    python3-rosinstall-generator \
    python3-vcstool \
    build-essential && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

#
# ROS 2 installation
#
RUN sudo locale-gen en_US en_US.UTF-8 && \
    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - && \
    sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
RUN apt-get update && apt-get install -y \
    ros-$ROS2_DISTRO-desktop \
    ros-$ROS2_DISTRO-rqt \
    ros-$ROS2_DISTRO-rmw-cyclonedds-cpp \
    ros-$ROS2_DISTRO-ros1-bridge \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-pip && \
    pip3 install -U argcomplete && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

#
# ROS dependency
#
RUN apt-get update && apt-get install -y \
    python3-rosdep \
    build-essential \
    cmake \
    git && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean
RUN sudo rosdep init && \
    rosdep update
 

CMD ["/bin/bash"]
