name: Docker Image Build Jobs.
on:
  push:
    tags:
      - '*'

jobs:
  build_intel_docker_image:
    runs-on: [self-hosted, Linux, X64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build docker
        run: make intel
      - name: Push docker_image
        run: make push_intel
  build_nvidia_docker_image:
    runs-on: [self-hosted, Linux, ARM64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build docker
        run: make nvidia
      - name: Push docker_image
        run: make push_nv
